
IMAGE_CODE_REDIS_EXPIRES = 300

SMS_CODE_REDIS_EXPIRES = 300

SMS_CODE_REDIS_FREQUENCY_LIMIT = 60

QINIU_DOMIN_PREFIX = 'http://default.cdn.com/'

HOME_PAGE_MAX_COUNT = 10

USER_FOLLOWED_MAX_COUNT = 4

USER_COLLECTION_MAX_NEWS = 10

OTHER_NEWS_PAGE_MAX_COUNT = 10

CLICK_RANK_MAX_NEWS = 10

ADMIN_USER_PAGE_MAX_COUNT = 10

ADMIN_NEWS_PAGE_MAX_COUNT = 10
